### PR TITLE
Don't call testBrowserInfo() on Safari.

### LINKED ISSUE #45: npm run test fails on macOS with Safari 10
Safari 10 mostly works with this package (after you've [enabled Remote Automation](https://webkit.org/blog/6900/webdriver-support-in-safari-10/)), taking advantage of the built-in webdriver that ships with macOS. There's a small modification that needs to be made to the tests to work around the fact that the webdriver doesn't expose browser info (at least not in the same way that other browsers do). The following needs to be skipped for Safari 10:

```js
function testBrowserInfo(specificBrowser) {
  const versionString = specificBrowser.getRawVersionString();
  (versionString === null).should.equal(false);

  const versionNumber = specificBrowser.getVersionNumber();
  versionNumber.should.not.equal(-1);
}
```

I'll put together a quick PR to blacklist that check for Safari, but if you have a better idea, @gauntface, I'm open to that as well.

### PR DESCRIPTION
**Pull request by jeffposnick**
R: @gauntface @addyosmani 

Fixes #45

### CODE REVIEW

**Comment by gauntface** [comment]
This will fail when run and safari is not set up correctly (hence why safari is disabled from testing on travis.)

Locally testing makes sense when you have safari configured correctly.

If it's a problem, it would be better to have npm run test set a flag of some kind for only automated tests (no safari or opera) and then add npm run test:manual that flags all browsers.

**Comment by jeffposnick** [comment]
I think I do have my local Safari 10 configured correctly:
-  `/usr/bin/safaridriver` was created automatically as part of the Safari 10 installation
- I had to manually turn on the Develop menu and enable "Allow Remote Auotmation"

All the other tests pass, so I don't think Safari 10 should be excluded entirely.

It's just that the webdriver methods for the Safari driver don't seem to support those mechanisms for getting the browser version. If you can massage the methods so that they work with Safari 10, that would be a good alternative to this PR, @gauntface. I can't figure out how to do so.

**Comment by gauntface** [comment]
I'll look at this as soon as I can.

It's not a selenium issue but rather an issue with how safari stashes it's version (it's in a .plist file)

**Comment by gauntface** [comment]
There was a regex issue (always a regex issue) where Safari had changed it's version number from "XX.X.X" to "XX.X". Fixed in master BUT the selenium webdriver piece is failing (plus my stable safari crashes on every boot and the "fix" is to re-install OS X according to forum posts).

**Pull request closed without merging**
